### ISSUE TITLE
can't run from cli

### ISSUE THREAD

**Issue by kitsguru** [princed/postcss-banner#90]
Moving from grunt to running all my build scripts as npm run commands.

The postcss-banner fails:
`Error: Loading PostCSS Plugin failed: Cannot find module 'postcssBanner'`

I believe there needs to be a .bin entry to run from the CLI

**Comment by princed** [comment]
Thank you for your issue!

I believe there's no need for separate CLI for each postcss plugin as they can be easily run using `postcss-cli` (via either config or `--use` flag), check its docs to find more on that: https://github.com/postcss/postcss-cli#usage.

Please do let me know if you have other questions.
